version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
    environment:
      POSTGRES_DB: "brinks"
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "hugo"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
