<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCZe0CbZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCZe0CbZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCZe0CbZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCZe0CbZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCZe0CbZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'CZe0CbZ',
    'container.build_id' => 'bc08c254',
    'container.build_time' => 1696017296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCZe0CbZ');
